import type { UniverseStock } from '../types/market';

/**
 * GENERATED FILE — do not edit by hand.
 * NIFTY 500 constituents (NSE official lists) minus the curated hand-written
 * universe in stocks.ts. Regenerate: node scripts/generate-universe.mjs
 * These entries power search/quotes/detail/watchlist; the portfolio engine,
 * screener and market snapshot use the curated subset only.
 */
export const NIFTY500_EXTENSION: UniverseStock[] = [
  { symbol: 'ABB', name: "ABB India", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABB.NS' },
  { symbol: 'ADANIENSOL', name: "Adani Energy Solutions", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ADANIENSOL.NS' },
  { symbol: 'ADANIENT', name: "Adani Enterprises", sector: 'METALS', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ADANIENT.NS' },
  { symbol: 'ADANIGREEN', name: "Adani Green Energy", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ADANIGREEN.NS' },
  { symbol: 'ADANIPORTS', name: "Adani Ports and Special Economic Zone", sector: 'INFRASTRUCTURE', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ADANIPORTS.NS' },
  { symbol: 'ADANIPOWER', name: "Adani Power", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ADANIPOWER.NS' },
  { symbol: 'AMBUJACEM', name: "Ambuja Cements", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AMBUJACEM.NS' },
  { symbol: 'ASIANPAINT', name: "Asian Paints", sector: 'CONSUMER', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ASIANPAINT.NS' },
  { symbol: 'BAJAJ-AUTO', name: "Bajaj Auto", sector: 'AUTO', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BAJAJ-AUTO.NS' },
  { symbol: 'BAJAJFINSV', name: "Bajaj Finserv", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BAJAJFINSV.NS' },
  { symbol: 'BAJAJHLDNG', name: "Bajaj Holdings & Investment", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BAJAJHLDNG.NS' },
  { symbol: 'BANKBARODA', name: "Bank of Baroda", sector: 'BANKING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BANKBARODA.NS' },
  { symbol: 'BPCL', name: "Bharat Petroleum Corporation", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BPCL.NS' },
  { symbol: 'BOSCHLTD', name: "Bosch", sector: 'AUTO', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BOSCHLTD.NS' },
  { symbol: 'BRITANNIA', name: "Britannia Industries", sector: 'FMCG', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BRITANNIA.NS' },
  { symbol: 'CGPOWER', name: "CG Power and Industrial Solutions", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CGPOWER.NS' },
  { symbol: 'CANBK', name: "Canara Bank", sector: 'BANKING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CANBK.NS' },
  { symbol: 'CHOLAFIN', name: "Cholamandalam Investment and Finance Company", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CHOLAFIN.NS' },
  { symbol: 'COALINDIA', name: "Coal India", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'COALINDIA.NS' },
  { symbol: 'CUMMINSIND', name: "Cummins India", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CUMMINSIND.NS' },
  { symbol: 'DLF', name: "DLF", sector: 'INFRASTRUCTURE', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DLF.NS' },
  { symbol: 'DIVISLAB', name: "Divi's Laboratories", sector: 'PHARMA', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DIVISLAB.NS' },
  { symbol: 'ETERNAL', name: "Eternal", sector: 'CONSUMER', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ETERNAL.NS' },
  { symbol: 'GAIL', name: "GAIL (India)", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GAIL.NS' },
  { symbol: 'GODREJCP', name: "Godrej Consumer Products", sector: 'FMCG', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GODREJCP.NS' },
  { symbol: 'GRASIM', name: "Grasim Industries", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GRASIM.NS' },
  { symbol: 'HDFCLIFE', name: "HDFC Life Insurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HDFCLIFE.NS' },
  { symbol: 'HINDZINC', name: "Hindustan Zinc", sector: 'METALS', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HINDZINC.NS' },
  { symbol: 'HYUNDAI', name: "Hyundai Motor India", sector: 'AUTO', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HYUNDAI.NS' },
  { symbol: 'INDHOTEL', name: "Indian Hotels Co.", sector: 'CONSUMER', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDHOTEL.NS' },
  { symbol: 'IOC', name: "Indian Oil Corporation", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IOC.NS' },
  { symbol: 'IRFC', name: "Indian Railway Finance Corporation", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IRFC.NS' },
  { symbol: 'INDIGO', name: "InterGlobe Aviation", sector: 'INFRASTRUCTURE', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDIGO.NS' },
  { symbol: 'JSWSTEEL', name: "JSW Steel", sector: 'METALS', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JSWSTEEL.NS' },
  { symbol: 'JINDALSTEL', name: "Jindal Steel", sector: 'METALS', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JINDALSTEL.NS' },
  { symbol: 'JIOFIN', name: "Jio Financial Services", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JIOFIN.NS' },
  { symbol: 'LTM', name: "LTM", sector: 'TECHNOLOGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LTM.NS' },
  { symbol: 'LODHA', name: "Lodha Developers", sector: 'INFRASTRUCTURE', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LODHA.NS' },
  { symbol: 'MAXHEALTH', name: "Max Healthcare Institute", sector: 'HEALTHCARE', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MAXHEALTH.NS' },
  { symbol: 'MAZDOCK', name: "Mazagoan Dock Shipbuilders", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MAZDOCK.NS' },
  { symbol: 'MUTHOOTFIN', name: "Muthoot Finance", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MUTHOOTFIN.NS' },
  { symbol: 'ONGC', name: "Oil & Natural Gas Corporation", sector: 'ENERGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ONGC.NS' },
  { symbol: 'PIDILITIND', name: "Pidilite Industries", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PIDILITIND.NS' },
  { symbol: 'PFC', name: "Power Finance Corporation", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PFC.NS' },
  { symbol: 'PNB', name: "Punjab National Bank", sector: 'BANKING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PNB.NS' },
  { symbol: 'RECLTD', name: "REC", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RECLTD.NS' },
  { symbol: 'SBILIFE', name: "SBI Life Insurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SBILIFE.NS' },
  { symbol: 'MOTHERSON', name: "Samvardhana Motherson International", sector: 'AUTO', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MOTHERSON.NS' },
  { symbol: 'SHREECEM', name: "Shree Cement", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SHREECEM.NS' },
  { symbol: 'SHRIRAMFIN', name: "Shriram Finance", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SHRIRAMFIN.NS' },
  { symbol: 'ENRIN', name: "Siemens Energy India", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ENRIN.NS' },
  { symbol: 'SIEMENS', name: "Siemens", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SIEMENS.NS' },
  { symbol: 'SOLARINDS', name: "Solar Industries India", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SOLARINDS.NS' },
  { symbol: 'TVSMOTOR', name: "TVS Motor Company", sector: 'AUTO', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TVSMOTOR.NS' },
  { symbol: 'TATACAP', name: "Tata Capital", sector: 'FINANCIAL_SERVICES', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TATACAP.NS' },
  { symbol: 'TATACONSUM', name: "Tata Consumer Products", sector: 'FMCG', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TATACONSUM.NS' },
  { symbol: 'TMCV', name: "Tata Motors", sector: 'MANUFACTURING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TMCV.NS' },
  { symbol: 'TMPV', name: "Tata Motors Passenger Vehicles", sector: 'AUTO', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TMPV.NS' },
  { symbol: 'TECHM', name: "Tech Mahindra", sector: 'TECHNOLOGY', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TECHM.NS' },
  { symbol: 'TORNTPHARM', name: "Torrent Pharmaceuticals", sector: 'PHARMA', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TORNTPHARM.NS' },
  { symbol: 'TRENT', name: "Trent", sector: 'CONSUMER', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TRENT.NS' },
  { symbol: 'UNIONBANK', name: "Union Bank of India", sector: 'BANKING', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'UNIONBANK.NS' },
  { symbol: 'UNITDSPR', name: "United Spirits", sector: 'FMCG', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'UNITDSPR.NS' },
  { symbol: 'VBL', name: "Varun Beverages", sector: 'FMCG', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'VBL.NS' },
  { symbol: 'VEDL', name: "Vedanta", sector: 'METALS', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'VEDL.NS' },
  { symbol: 'ZYDUSLIFE', name: "Zydus Lifesciences", sector: 'PHARMA', mcap: 'LARGE', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ZYDUSLIFE.NS' },
  { symbol: '360ONE', name: "360 ONE WAM", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: '360ONE.NS' },
  { symbol: '3MINDIA', name: "3M India", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: '3MINDIA.NS' },
  { symbol: 'ACC', name: "ACC", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ACC.NS' },
  { symbol: 'AIAENG', name: "AIA Engineering", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AIAENG.NS' },
  { symbol: 'APLAPOLLO', name: "APL Apollo Tubes", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'APLAPOLLO.NS' },
  { symbol: 'AUBANK', name: "AU Small Finance Bank", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AUBANK.NS' },
  { symbol: 'AWL', name: "AWL Agri Business", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AWL.NS' },
  { symbol: 'ABBOTINDIA', name: "Abbott India", sector: 'HEALTHCARE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABBOTINDIA.NS' },
  { symbol: 'ATGL', name: "Adani Total Gas", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ATGL.NS' },
  { symbol: 'ABCAPITAL', name: "Aditya Birla Capital", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABCAPITAL.NS' },
  { symbol: 'AJANTPHARM', name: "Ajanta Pharmaceuticals", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AJANTPHARM.NS' },
  { symbol: 'ALKEM', name: "Alkem Laboratories", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ALKEM.NS' },
  { symbol: 'ANTHEM', name: "Anthem Biosciences", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ANTHEM.NS' },
  { symbol: 'APARINDS', name: "Apar Industries", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'APARINDS.NS' },
  { symbol: 'APOLLOTYRE', name: "Apollo Tyres", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'APOLLOTYRE.NS' },
  { symbol: 'ASHOKLEY', name: "Ashok Leyland", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ASHOKLEY.NS' },
  { symbol: 'AUROPHARMA', name: "Aurobindo Pharma", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AUROPHARMA.NS' },
  { symbol: 'AIIL', name: "Authum Investment & Infrastructure", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AIIL.NS' },
  { symbol: 'BSE', name: "BSE", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BSE.NS' },
  { symbol: 'BAJAJHFL', name: "Bajaj Housing Finance", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BAJAJHFL.NS' },
  { symbol: 'BALKRISIND', name: "Balkrishna Industries", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BALKRISIND.NS' },
  { symbol: 'BANKINDIA', name: "Bank of India", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BANKINDIA.NS' },
  { symbol: 'MAHABANK', name: "Bank of Maharashtra", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MAHABANK.NS' },
  { symbol: 'BERGEPAINT', name: "Berger Paints India", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BERGEPAINT.NS' },
  { symbol: 'BDL', name: "Bharat Dynamics", sector: 'DEFENCE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BDL.NS' },
  { symbol: 'BHARATFORG', name: "Bharat Forge", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BHARATFORG.NS' },
  { symbol: 'BHEL', name: "Bharat Heavy Electricals", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BHEL.NS' },
  { symbol: 'BHARTIHEXA', name: "Bharti Hexacom", sector: 'TELECOM', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BHARTIHEXA.NS' },
  { symbol: 'GROWW', name: "Billionbrains Garage Ventures", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GROWW.NS' },
  { symbol: 'BIOCON', name: "Biocon", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BIOCON.NS' },
  { symbol: 'BLUESTARCO', name: "Blue Star", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BLUESTARCO.NS' },
  { symbol: 'CRISIL', name: "CRISIL", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CRISIL.NS' },
  { symbol: 'COCHINSHIP', name: "Cochin Shipyard", sector: 'DEFENCE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'COCHINSHIP.NS' },
  { symbol: 'COFORGE', name: "Coforge", sector: 'TECHNOLOGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'COFORGE.NS' },
  { symbol: 'COLPAL', name: "Colgate Palmolive (India)", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'COLPAL.NS' },
  { symbol: 'CONCOR', name: "Container Corporation of India", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CONCOR.NS' },
  { symbol: 'COROMANDEL', name: "Coromandel International", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'COROMANDEL.NS' },
  { symbol: 'DABUR', name: "Dabur India", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DABUR.NS' },
  { symbol: 'DALBHARAT', name: "Dalmia Bharat", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DALBHARAT.NS' },
  { symbol: 'DIXON', name: "Dixon Technologies (India)", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DIXON.NS' },
  { symbol: 'ENDURANCE', name: "Endurance Technologies", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ENDURANCE.NS' },
  { symbol: 'ESCORTS', name: "Escorts Kubota", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ESCORTS.NS' },
  { symbol: 'EXIDEIND', name: "Exide Industries", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'EXIDEIND.NS' },
  { symbol: 'NYKAA', name: "FSN E-Commerce Ventures", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NYKAA.NS' },
  { symbol: 'FEDERALBNK', name: "Federal Bank", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FEDERALBNK.NS' },
  { symbol: 'FORTIS', name: "Fortis Healthcare", sector: 'HEALTHCARE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FORTIS.NS' },
  { symbol: 'GVT&D', name: "GE Vernova T&D India", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GVT&D.NS' },
  { symbol: 'GMRAIRPORT', name: "GMR Airports", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GMRAIRPORT.NS' },
  { symbol: 'GICRE', name: "General Insurance Corporation of India", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GICRE.NS' },
  { symbol: 'GLAXO', name: "Glaxosmithkline Pharmaceuticals", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GLAXO.NS' },
  { symbol: 'GLENMARK', name: "Glenmark Pharmaceuticals", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GLENMARK.NS' },
  { symbol: 'MEDANTA', name: "Global Health", sector: 'HEALTHCARE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MEDANTA.NS' },
  { symbol: 'GODFRYPHLP', name: "Godfrey Phillips India", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GODFRYPHLP.NS' },
  { symbol: 'GODREJIND', name: "Godrej Industries", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GODREJIND.NS' },
  { symbol: 'GODREJPROP', name: "Godrej Properties", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GODREJPROP.NS' },
  { symbol: 'FLUOROCHEM', name: "Gujarat Fluorochemicals", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FLUOROCHEM.NS' },
  { symbol: 'HDBFS', name: "HDB Financial Services", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HDBFS.NS' },
  { symbol: 'HAVELLS', name: "Havells India", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HAVELLS.NS' },
  { symbol: 'HEROMOTOCO', name: "Hero MotoCorp", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HEROMOTOCO.NS' },
  { symbol: 'HEXT', name: "Hexaware Technologies", sector: 'TECHNOLOGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HEXT.NS' },
  { symbol: 'HINDPETRO', name: "Hindustan Petroleum Corporation", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HINDPETRO.NS' },
  { symbol: 'POWERINDIA', name: "Hitachi Energy India", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'POWERINDIA.NS' },
  { symbol: 'HONAUT', name: "Honeywell Automation India", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HONAUT.NS' },
  { symbol: 'HUDCO', name: "Housing & Urban Development Corporation", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HUDCO.NS' },
  { symbol: 'ICICIGI', name: "ICICI Lombard General Insurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ICICIGI.NS' },
  { symbol: 'ICICIAMC', name: "ICICI Prudential Asset Management Company", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ICICIAMC.NS' },
  { symbol: 'ICICIPRULI', name: "ICICI Prudential Life Insurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ICICIPRULI.NS' },
  { symbol: 'IDFCFIRSTB', name: "IDFC First Bank", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IDFCFIRSTB.NS' },
  { symbol: 'ITCHOTELS', name: "ITC Hotels", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ITCHOTELS.NS' },
  { symbol: 'INDIANB', name: "Indian Bank", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDIANB.NS' },
  { symbol: 'IRCTC', name: "Indian Railway Catering And Tourism Corporation", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IRCTC.NS' },
  { symbol: 'IREDA', name: "Indian Renewable Energy Development Agency", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IREDA.NS' },
  { symbol: 'INDUSTOWER', name: "Indus Towers", sector: 'TELECOM', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDUSTOWER.NS' },
  { symbol: 'INDUSINDBK', name: "IndusInd Bank", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDUSINDBK.NS' },
  { symbol: 'NAUKRI', name: "Info Edge (India)", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NAUKRI.NS' },
  { symbol: 'IPCALAB', name: "Ipca Laboratories", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IPCALAB.NS' },
  { symbol: 'JKCEMENT', name: "J.K. Cement", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JKCEMENT.NS' },
  { symbol: 'JSWENERGY', name: "JSW Energy", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JSWENERGY.NS' },
  { symbol: 'JSWINFRA', name: "JSW Infrastructure", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JSWINFRA.NS' },
  { symbol: 'JSL', name: "Jindal Stainless", sector: 'METALS', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JSL.NS' },
  { symbol: 'JUBLFOOD', name: "Jubilant Foodworks", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JUBLFOOD.NS' },
  { symbol: 'KPRMILL', name: "K.P.R. Mill", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KPRMILL.NS' },
  { symbol: 'KEI', name: "KEI Industries", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KEI.NS' },
  { symbol: 'KPITTECH', name: "KPIT Technologies", sector: 'TECHNOLOGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KPITTECH.NS' },
  { symbol: 'KALYANKJIL', name: "Kalyan Jewellers India", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KALYANKJIL.NS' },
  { symbol: 'LTF', name: "L&T Finance", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LTF.NS' },
  { symbol: 'LTTS', name: "L&T Technology Services", sector: 'TECHNOLOGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LTTS.NS' },
  { symbol: 'LGEINDIA', name: "LG Electronics India", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LGEINDIA.NS' },
  { symbol: 'LICHSGFIN', name: "LIC Housing Finance", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LICHSGFIN.NS' },
  { symbol: 'LAURUSLABS', name: "Laurus Labs", sector: 'HEALTHCARE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LAURUSLABS.NS' },
  { symbol: 'LENSKART', name: "Lenskart Solutions", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LENSKART.NS' },
  { symbol: 'LICI', name: "Life Insurance Corporation of India", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LICI.NS' },
  { symbol: 'LINDEINDIA', name: "Linde India", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LINDEINDIA.NS' },
  { symbol: 'LLOYDSME', name: "Lloyds Metals And Energy", sector: 'METALS', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LLOYDSME.NS' },
  { symbol: 'LUPIN', name: "Lupin", sector: 'HEALTHCARE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LUPIN.NS' },
  { symbol: 'MRF', name: "MRF", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MRF.NS' },
  { symbol: 'M&MFIN', name: "Mahindra & Mahindra Financial Services", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'M&MFIN.NS' },
  { symbol: 'MANKIND', name: "Mankind Pharma", sector: 'PHARMA', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MANKIND.NS' },
  { symbol: 'MARICO', name: "Marico", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MARICO.NS' },
  { symbol: 'MFSL', name: "Max Financial Services", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MFSL.NS' },
  { symbol: 'MOTILALOFS', name: "Motilal Oswal Financial Services", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MOTILALOFS.NS' },
  { symbol: 'MPHASIS', name: "MphasiS", sector: 'TECHNOLOGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MPHASIS.NS' },
  { symbol: 'MCX', name: "Multi Commodity Exchange of India", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MCX.NS' },
  { symbol: 'NHPC', name: "NHPC", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NHPC.NS' },
  { symbol: 'NLCINDIA', name: "NLC India", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NLCINDIA.NS' },
  { symbol: 'NMDC', name: "NMDC", sector: 'METALS', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NMDC.NS' },
  { symbol: 'NTPCGREEN', name: "NTPC Green Energy", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NTPCGREEN.NS' },
  { symbol: 'NATIONALUM', name: "National Aluminium Co.", sector: 'METALS', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NATIONALUM.NS' },
  { symbol: 'NAM-INDIA', name: "Nippon Life India Asset Management", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NAM-INDIA.NS' },
  { symbol: 'OBEROIRLTY', name: "Oberoi Realty", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'OBEROIRLTY.NS' },
  { symbol: 'OIL', name: "Oil India", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'OIL.NS' },
  { symbol: 'PAYTM', name: "One 97 Communications", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PAYTM.NS' },
  { symbol: 'OFSS', name: "Oracle Financial Services Software", sector: 'TECHNOLOGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'OFSS.NS' },
  { symbol: 'POLICYBZR', name: "PB Fintech", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'POLICYBZR.NS' },
  { symbol: 'PIIND', name: "PI Industries", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PIIND.NS' },
  { symbol: 'PAGEIND', name: "Page Industries", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PAGEIND.NS' },
  { symbol: 'PATANJALI', name: "Patanjali Foods", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PATANJALI.NS' },
  { symbol: 'PETRONET', name: "Petronet LNG", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PETRONET.NS' },
  { symbol: 'PHOENIXLTD', name: "Phoenix Mills", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PHOENIXLTD.NS' },
  { symbol: 'PREMIERENE', name: "Premier Energies", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PREMIERENE.NS' },
  { symbol: 'PRESTIGE', name: "Prestige Estates Projects", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PRESTIGE.NS' },
  { symbol: 'RADICO', name: "Radico Khaitan", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RADICO.NS' },
  { symbol: 'RVNL', name: "Rail Vikas Nigam", sector: 'INFRASTRUCTURE', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RVNL.NS' },
  { symbol: 'SBICARD', name: "SBI Cards and Payment Services", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SBICARD.NS' },
  { symbol: 'SJVN', name: "SJVN", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SJVN.NS' },
  { symbol: 'SRF', name: "SRF", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SRF.NS' },
  { symbol: 'SCHAEFFLER', name: "Schaeffler India", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SCHAEFFLER.NS' },
  { symbol: 'SAIL', name: "Steel Authority of India", sector: 'METALS', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SAIL.NS' },
  { symbol: 'SUNDARMFIN', name: "Sundaram Finance", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SUNDARMFIN.NS' },
  { symbol: 'SUPREMEIND', name: "Supreme Industries", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SUPREMEIND.NS' },
  { symbol: 'SUZLON', name: "Suzlon Energy", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SUZLON.NS' },
  { symbol: 'SWIGGY', name: "Swiggy", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SWIGGY.NS' },
  { symbol: 'TATACOMM', name: "Tata Communications", sector: 'TELECOM', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TATACOMM.NS' },
  { symbol: 'TATAINVEST', name: "Tata Investment Corporation", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TATAINVEST.NS' },
  { symbol: 'NIACL', name: "The New India Assurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NIACL.NS' },
  { symbol: 'THERMAX', name: "Thermax", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'THERMAX.NS' },
  { symbol: 'TORNTPOWER', name: "Torrent Power", sector: 'ENERGY', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TORNTPOWER.NS' },
  { symbol: 'TIINDIA', name: "Tube Investments of India", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TIINDIA.NS' },
  { symbol: 'UNOMINDA', name: "UNO Minda", sector: 'AUTO', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'UNOMINDA.NS' },
  { symbol: 'UPL', name: "UPL", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'UPL.NS' },
  { symbol: 'UBL', name: "United Breweries", sector: 'FMCG', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'UBL.NS' },
  { symbol: 'VMM', name: "Vishal Mega Mart", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'VMM.NS' },
  { symbol: 'IDEA', name: "Vodafone Idea", sector: 'TELECOM', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IDEA.NS' },
  { symbol: 'VOLTAS', name: "Voltas", sector: 'CONSUMER', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'VOLTAS.NS' },
  { symbol: 'WAAREEENER', name: "Waaree Energies", sector: 'MANUFACTURING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'WAAREEENER.NS' },
  { symbol: 'YESBANK', name: "Yes Bank", sector: 'BANKING', mcap: 'MID', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'YESBANK.NS' },
  { symbol: 'ACMESOLAR', name: "ACME Solar Holdings", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ACMESOLAR.NS' },
  { symbol: 'AADHARHFC', name: "Aadhar Housing Finance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AADHARHFC.NS' },
  { symbol: 'AARTIIND', name: "Aarti Industries", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AARTIIND.NS' },
  { symbol: 'AAVAS', name: "Aavas Financiers", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AAVAS.NS' },
  { symbol: 'ACE', name: "Action Construction Equipment", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ACE.NS' },
  { symbol: 'ACUTAAS', name: "Acutaas Chemicals", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ACUTAAS.NS' },
  { symbol: 'ABFRL', name: "Aditya Birla Fashion and Retail", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABFRL.NS' },
  { symbol: 'ABLBL', name: "Aditya Birla Lifestyle Brands", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABLBL.NS' },
  { symbol: 'ABREL', name: "Aditya Birla Real Estate", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABREL.NS' },
  { symbol: 'ABSLAMC', name: "Aditya Birla Sun Life AMC", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABSLAMC.NS' },
  { symbol: 'CPPLUS', name: "Aditya Infotech", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CPPLUS.NS' },
  { symbol: 'AEGISLOG', name: "Aegis Logistics", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AEGISLOG.NS' },
  { symbol: 'AEGISVOPAK', name: "Aegis Vopak Terminals", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AEGISVOPAK.NS' },
  { symbol: 'AFCONS', name: "Afcons Infrastructure", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AFCONS.NS' },
  { symbol: 'AFFLE', name: "Affle 3i", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AFFLE.NS' },
  { symbol: 'ABDL', name: "Allied Blenders and Distillers", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ABDL.NS' },
  { symbol: 'ARE&M', name: "Amara Raja Energy & Mobility", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ARE&M.NS' },
  { symbol: 'AMBER', name: "Amber Enterprises India", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'AMBER.NS' },
  { symbol: 'ANANDRATHI', name: "Anand Rathi Wealth", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ANANDRATHI.NS' },
  { symbol: 'ANANTRAJ', name: "Anant Raj", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ANANTRAJ.NS' },
  { symbol: 'ANGELONE', name: "Angel One", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ANGELONE.NS' },
  { symbol: 'ANURAS', name: "Anupam Rasayan India", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ANURAS.NS' },
  { symbol: 'APTUS', name: "Aptus Value Housing Finance India", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'APTUS.NS' },
  { symbol: 'ASAHIINDIA', name: "Asahi India Glass", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ASAHIINDIA.NS' },
  { symbol: 'ASTERDM', name: "Aster DM Quality Care", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ASTERDM.NS' },
  { symbol: 'ATHERENERG', name: "Ather Energy", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ATHERENERG.NS' },
  { symbol: 'ATUL', name: "Atul", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ATUL.NS' },
  { symbol: 'BEML', name: "BEML", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BEML.NS' },
  { symbol: 'BLS', name: "BLS International Services", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BLS.NS' },
  { symbol: 'BALRAMCHIN', name: "Balrampur Chini Mills", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BALRAMCHIN.NS' },
  { symbol: 'BANDHANBNK', name: "Bandhan Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BANDHANBNK.NS' },
  { symbol: 'BATAINDIA', name: "Bata India", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BATAINDIA.NS' },
  { symbol: 'BAYERCROP', name: "Bayer Cropscience", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BAYERCROP.NS' },
  { symbol: 'BELRISE', name: "Belrise Industries", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BELRISE.NS' },
  { symbol: 'BIKAJI', name: "Bikaji Foods International", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BIKAJI.NS' },
  { symbol: 'BSOFT', name: "Birlasoft", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BSOFT.NS' },
  { symbol: 'BLUEDART', name: "Blue Dart Express", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BLUEDART.NS' },
  { symbol: 'BLUEJET', name: "Blue Jet Healthcare", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BLUEJET.NS' },
  { symbol: 'BBTC', name: "Bombay Burmah Trading Corporation", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BBTC.NS' },
  { symbol: 'FIRSTCRY', name: "Brainbees Solutions", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FIRSTCRY.NS' },
  { symbol: 'BRIGADE', name: "Brigade Enterprises", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'BRIGADE.NS' },
  { symbol: 'MAPMYINDIA', name: "C.E. Info Systems", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MAPMYINDIA.NS' },
  { symbol: 'CCL', name: "CCL Products (I)", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CCL.NS' },
  { symbol: 'CESC', name: "CESC", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CESC.NS' },
  { symbol: 'CIEINDIA', name: "CIE Automotive India", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CIEINDIA.NS' },
  { symbol: 'CANFINHOME', name: "Can Fin Homes", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CANFINHOME.NS' },
  { symbol: 'CANHLIFE', name: "Canara HSBC Life Insurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CANHLIFE.NS' },
  { symbol: 'CAPLIPOINT', name: "Caplin Point Laboratories", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CAPLIPOINT.NS' },
  { symbol: 'CGCL', name: "Capri Global Capital", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CGCL.NS' },
  { symbol: 'CARBORUNIV', name: "Carborundum Universal", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CARBORUNIV.NS' },
  { symbol: 'CARTRADE', name: "Cartrade Tech", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CARTRADE.NS' },
  { symbol: 'CASTROLIND', name: "Castrol India", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CASTROLIND.NS' },
  { symbol: 'CEATLTD', name: "Ceat", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CEATLTD.NS' },
  { symbol: 'CEMPRO', name: "Cemindia Projects", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CEMPRO.NS' },
  { symbol: 'CENTRALBK', name: "Central Bank of India", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CENTRALBK.NS' },
  { symbol: 'CHALET', name: "Chalet Hotels", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CHALET.NS' },
  { symbol: 'CHAMBLFERT', name: "Chambal Fertilizers & Chemicals", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CHAMBLFERT.NS' },
  { symbol: 'CHENNPETRO', name: "Chennai Petroleum Corporation", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CHENNPETRO.NS' },
  { symbol: 'CHOICEIN', name: "Choice International", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CHOICEIN.NS' },
  { symbol: 'CHOLAHLDNG', name: "Cholamandalam Financial Holdings", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CHOLAHLDNG.NS' },
  { symbol: 'CUB', name: "City Union Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CUB.NS' },
  { symbol: 'CLEAN', name: "Clean Science and Technology", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CLEAN.NS' },
  { symbol: 'COHANCE', name: "Cohance Lifesciences", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'COHANCE.NS' },
  { symbol: 'CAMS', name: "Computer Age Management Services", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CAMS.NS' },
  { symbol: 'CONCORDBIO', name: "Concord Biotech", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CONCORDBIO.NS' },
  { symbol: 'CRAFTSMAN', name: "Craftsman Automation", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CRAFTSMAN.NS' },
  { symbol: 'CREDITACC', name: "CreditAccess Grameen", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CREDITACC.NS' },
  { symbol: 'CROMPTON', name: "Crompton Greaves Consumer Electricals", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CROMPTON.NS' },
  { symbol: 'CYIENT', name: "Cyient", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'CYIENT.NS' },
  { symbol: 'DCMSHRIRAM', name: "DCM Shriram", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DCMSHRIRAM.NS' },
  { symbol: 'DOMS', name: "DOMS Industries", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DOMS.NS' },
  { symbol: 'DATAPATTNS', name: "Data Patterns (India)", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DATAPATTNS.NS' },
  { symbol: 'DEEPAKFERT', name: "Deepak Fertilisers & Petrochemicals Corp.", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DEEPAKFERT.NS' },
  { symbol: 'DEEPAKNTR', name: "Deepak Nitrite", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DEEPAKNTR.NS' },
  { symbol: 'DELHIVERY', name: "Delhivery", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DELHIVERY.NS' },
  { symbol: 'DEVYANI', name: "Devyani International", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'DEVYANI.NS' },
  { symbol: 'EIDPARRY', name: "E.I.D. Parry (India)", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'EIDPARRY.NS' },
  { symbol: 'EIHOTEL', name: "EIH", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'EIHOTEL.NS' },
  { symbol: 'ELECON', name: "Elecon Engineering Co.", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ELECON.NS' },
  { symbol: 'ELGIEQUIP', name: "Elgi Equipments", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ELGIEQUIP.NS' },
  { symbol: 'EMAMILTD', name: "Emami", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'EMAMILTD.NS' },
  { symbol: 'EMCURE', name: "Emcure Pharmaceuticals", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'EMCURE.NS' },
  { symbol: 'EMMVEE', name: "Emmvee Photovoltaic Power", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'EMMVEE.NS' },
  { symbol: 'ENGINERSIN', name: "Engineers India", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ENGINERSIN.NS' },
  { symbol: 'ERIS', name: "Eris Lifesciences", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ERIS.NS' },
  { symbol: 'FACT', name: "Fertilisers and Chemicals Travancore", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FACT.NS' },
  { symbol: 'FINCABLES', name: "Finolex Cables", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FINCABLES.NS' },
  { symbol: 'FSL', name: "Firstsource Solutions", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FSL.NS' },
  { symbol: 'FIVESTAR', name: "Five-Star Business Finance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FIVESTAR.NS' },
  { symbol: 'FORCEMOT', name: "Force Motors", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'FORCEMOT.NS' },
  { symbol: 'GABRIEL', name: "Gabriel India", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GABRIEL.NS' },
  { symbol: 'GALLANTT', name: "Gallantt Ispat", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GALLANTT.NS' },
  { symbol: 'GRSE', name: "Garden Reach Shipbuilders & Engineers", sector: 'DEFENCE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GRSE.NS' },
  { symbol: 'GILLETTE', name: "Gillette India", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GILLETTE.NS' },
  { symbol: 'GLAND', name: "Gland Pharma", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GLAND.NS' },
  { symbol: 'GODIGIT', name: "Go Digit General Insurance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GODIGIT.NS' },
  { symbol: 'GPIL', name: "Godawari Power & Ispat", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GPIL.NS' },
  { symbol: 'GRANULES', name: "Granules India", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GRANULES.NS' },
  { symbol: 'GRAPHITE', name: "Graphite India", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GRAPHITE.NS' },
  { symbol: 'GRAVITA', name: "Gravita India", sector: 'METALS', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GRAVITA.NS' },
  { symbol: 'GESHIP', name: "Great Eastern Shipping Co.", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GESHIP.NS' },
  { symbol: 'GMDCLTD', name: "Gujarat Mineral Development Corporation", sector: 'METALS', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'GMDCLTD.NS' },
  { symbol: 'HEG', name: "H.E.G.", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HEG.NS' },
  { symbol: 'HBLENGINE', name: "HBL Engineering", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HBLENGINE.NS' },
  { symbol: 'HFCL', name: "HFCL", sector: 'TELECOM', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HFCL.NS' },
  { symbol: 'HSCL', name: "Himadri Speciality Chemical", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HSCL.NS' },
  { symbol: 'HINDCOPPER', name: "Hindustan Copper", sector: 'METALS', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HINDCOPPER.NS' },
  { symbol: 'HOMEFIRST', name: "Home First Finance Company India", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HOMEFIRST.NS' },
  { symbol: 'HONASA', name: "Honasa Consumer", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'HONASA.NS' },
  { symbol: 'IDBI', name: "IDBI Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IDBI.NS' },
  { symbol: 'IFCI', name: "IFCI", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IFCI.NS' },
  { symbol: 'IIFL', name: "IIFL Finance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IIFL.NS' },
  { symbol: 'IRB', name: "IRB Infrastructure Developers", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IRB.NS' },
  { symbol: 'IRCON', name: "IRCON International", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IRCON.NS' },
  { symbol: 'ITI', name: "ITI", sector: 'TELECOM', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ITI.NS' },
  { symbol: 'INDGN', name: "Indegene", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDGN.NS' },
  { symbol: 'INDIACEM', name: "India Cements", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDIACEM.NS' },
  { symbol: 'INDIAMART', name: "Indiamart Intermesh", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INDIAMART.NS' },
  { symbol: 'IEX', name: "Indian Energy Exchange", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IEX.NS' },
  { symbol: 'IOB', name: "Indian Overseas Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IOB.NS' },
  { symbol: 'IGL', name: "Indraprastha Gas", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IGL.NS' },
  { symbol: 'INOXWIND', name: "Inox Wind", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INOXWIND.NS' },
  { symbol: 'INTELLECT', name: "Intellect Design Arena", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'INTELLECT.NS' },
  { symbol: 'IGIL', name: "International Gemological Institute", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IGIL.NS' },
  { symbol: 'IKS', name: "Inventurus Knowledge Solutions", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'IKS.NS' },
  { symbol: 'JBMA', name: "JBM Auto", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JBMA.NS' },
  { symbol: 'JKTYRE', name: "JK Tyre & Industries", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JKTYRE.NS' },
  { symbol: 'JMFINANCIL', name: "JM Financial", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JMFINANCIL.NS' },
  { symbol: 'JSWCEMENT', name: "JSW Cement", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JSWCEMENT.NS' },
  { symbol: 'JSWDULUX', name: "JSW Dulux", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JSWDULUX.NS' },
  { symbol: 'JAINREC', name: "Jain Resource Recycling", sector: 'METALS', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JAINREC.NS' },
  { symbol: 'JPPOWER', name: "Jaiprakash Power Ventures", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JPPOWER.NS' },
  { symbol: 'J&KBANK', name: "Jammu & Kashmir Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'J&KBANK.NS' },
  { symbol: 'JINDALSAW', name: "Jindal Saw", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JINDALSAW.NS' },
  { symbol: 'JUBLINGREA', name: "Jubilant Ingrevia", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JUBLINGREA.NS' },
  { symbol: 'JUBLPHARMA', name: "Jubilant Pharmova", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JUBLPHARMA.NS' },
  { symbol: 'JWL', name: "Jupiter Wagons", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JWL.NS' },
  { symbol: 'JYOTICNC', name: "Jyoti CNC Automation", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'JYOTICNC.NS' },
  { symbol: 'KAJARIACER', name: "Kajaria Ceramics", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KAJARIACER.NS' },
  { symbol: 'KPIL', name: "Kalpataru Projects International", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KPIL.NS' },
  { symbol: 'KARURVYSYA', name: "Karur Vysya Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KARURVYSYA.NS' },
  { symbol: 'KAYNES', name: "Kaynes Technology India", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KAYNES.NS' },
  { symbol: 'KEC', name: "Kec International", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KEC.NS' },
  { symbol: 'KFINTECH', name: "Kfin Technologies", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KFINTECH.NS' },
  { symbol: 'KIRLOSENG', name: "Kirloskar Oil Eng", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KIRLOSENG.NS' },
  { symbol: 'KIMS', name: "Krishna Institute of Medical Sciences", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'KIMS.NS' },
  { symbol: 'LTFOODS', name: "LT Foods", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LTFOODS.NS' },
  { symbol: 'LATENTVIEW', name: "Latent View Analytics", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LATENTVIEW.NS' },
  { symbol: 'THELEELA', name: "Leela Palaces Hotels & Resorts", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'THELEELA.NS' },
  { symbol: 'LEMONTREE', name: "Lemon Tree Hotels", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'LEMONTREE.NS' },
  { symbol: 'MMTC', name: "MMTC", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MMTC.NS' },
  { symbol: 'MGL', name: "Mahanagar Gas", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MGL.NS' },
  { symbol: 'MANAPPURAM', name: "Manappuram Finance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MANAPPURAM.NS' },
  { symbol: 'MRPL', name: "Mangalore Refinery & Petrochemicals", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MRPL.NS' },
  { symbol: 'MEESHO', name: "Meesho", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MEESHO.NS' },
  { symbol: 'MINDACORP', name: "Minda Corporation", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MINDACORP.NS' },
  { symbol: 'MSUMI', name: "Motherson Sumi Wiring India", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'MSUMI.NS' },
  { symbol: 'NATCOPHARM', name: "NATCO Pharma", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NATCOPHARM.NS' },
  { symbol: 'NBCC', name: "NBCC (India)", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NBCC.NS' },
  { symbol: 'NCC', name: "NCC", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NCC.NS' },
  { symbol: 'NSLNISP', name: "NMDC Steel", sector: 'METALS', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NSLNISP.NS' },
  { symbol: 'NH', name: "Narayana Hrudayalaya", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NH.NS' },
  { symbol: 'NAVA', name: "Nava", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NAVA.NS' },
  { symbol: 'NAVINFLUOR', name: "Navin Fluorine International", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NAVINFLUOR.NS' },
  { symbol: 'NETWEB', name: "Netweb Technologies India", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NETWEB.NS' },
  { symbol: 'NEULANDLAB', name: "Neuland Laboratories", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NEULANDLAB.NS' },
  { symbol: 'NEWGEN', name: "Newgen Software Technologies", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NEWGEN.NS' },
  { symbol: 'NIVABUPA', name: "Niva Bupa Health Insurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NIVABUPA.NS' },
  { symbol: 'NUVAMA', name: "Nuvama Wealth Management", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NUVAMA.NS' },
  { symbol: 'NUVOCO', name: "Nuvoco Vistas Corporation", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'NUVOCO.NS' },
  { symbol: 'OLAELEC', name: "Ola Electric Mobility", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'OLAELEC.NS' },
  { symbol: 'OLECTRA', name: "Olectra Greentech", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'OLECTRA.NS' },
  { symbol: 'ONESOURCE', name: "Onesource Specialty Pharma", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ONESOURCE.NS' },
  { symbol: 'PCBL', name: "PCBL Chemical", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PCBL.NS' },
  { symbol: 'PGEL', name: "PG Electroplast", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PGEL.NS' },
  { symbol: 'PNBHOUSING', name: "PNB Housing Finance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PNBHOUSING.NS' },
  { symbol: 'PTCIL', name: "PTC Industries", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PTCIL.NS' },
  { symbol: 'PVRINOX', name: "PVR INOX", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PVRINOX.NS' },
  { symbol: 'PARADEEP', name: "Paradeep Phosphates", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PARADEEP.NS' },
  { symbol: 'PFIZER', name: "Pfizer", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PFIZER.NS' },
  { symbol: 'PWL', name: "Physicswallah", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PWL.NS' },
  { symbol: 'PINELABS', name: "Pine Labs", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PINELABS.NS' },
  { symbol: 'PIRAMALFIN', name: "Piramal Finance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PIRAMALFIN.NS' },
  { symbol: 'PPLPHARMA', name: "Piramal Pharma", sector: 'PHARMA', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PPLPHARMA.NS' },
  { symbol: 'POLYMED', name: "Poly Medicure", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'POLYMED.NS' },
  { symbol: 'POONAWALLA', name: "Poonawalla Fincorp", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'POONAWALLA.NS' },
  { symbol: 'PFOCUS', name: "Prime Focus", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'PFOCUS.NS' },
  { symbol: 'RRKABEL', name: "R R Kabel", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RRKABEL.NS' },
  { symbol: 'RBLBANK', name: "RBL Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RBLBANK.NS' },
  { symbol: 'RHIM', name: "RHI MAGNESITA INDIA", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RHIM.NS' },
  { symbol: 'RITES', name: "RITES", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RITES.NS' },
  { symbol: 'RAILTEL', name: "Railtel Corporation Of India", sector: 'TELECOM', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RAILTEL.NS' },
  { symbol: 'RAINBOW', name: "Rainbow Childrens Medicare", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RAINBOW.NS' },
  { symbol: 'RKFORGE', name: "Ramkrishna Forgings", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RKFORGE.NS' },
  { symbol: 'REDINGTON', name: "Redington", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'REDINGTON.NS' },
  { symbol: 'RPOWER', name: "Reliance Power", sector: 'ENERGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RPOWER.NS' },
  { symbol: 'SBFC', name: "SBFC Finance", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SBFC.NS' },
  { symbol: 'SAGILITY', name: "Sagility", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SAGILITY.NS' },
  { symbol: 'SAILIFE', name: "Sai Life Sciences", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SAILIFE.NS' },
  { symbol: 'SAMMAANCAP', name: "Sammaan Capital", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SAMMAANCAP.NS' },
  { symbol: 'SAPPHIRE', name: "Sapphire Foods India", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SAPPHIRE.NS' },
  { symbol: 'SARDAEN', name: "Sarda Energy and Minerals", sector: 'METALS', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SARDAEN.NS' },
  { symbol: 'SAREGAMA', name: "Saregama India", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SAREGAMA.NS' },
  { symbol: 'SCHNEIDER', name: "Schneider Electric Infrastructure", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SCHNEIDER.NS' },
  { symbol: 'SCI', name: "Shipping Corporation of India", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SCI.NS' },
  { symbol: 'SHYAMMETL', name: "Shyam Metalics and Energy", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SHYAMMETL.NS' },
  { symbol: 'SIGNATURE', name: "Signatureglobal (India)", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SIGNATURE.NS' },
  { symbol: 'SOBHA', name: "Sobha", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SOBHA.NS' },
  { symbol: 'SONACOMS', name: "Sona BLW Precision Forgings", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SONACOMS.NS' },
  { symbol: 'SONATSOFTW', name: "Sonata Software", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SONATSOFTW.NS' },
  { symbol: 'STARHEALTH', name: "Star Health and Allied Insurance Company", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'STARHEALTH.NS' },
  { symbol: 'SUMICHEM', name: "Sumitomo Chemical India", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SUMICHEM.NS' },
  { symbol: 'SUNTV', name: "Sun TV Network", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SUNTV.NS' },
  { symbol: 'SPLPETRO', name: "Supreme Petrochem", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SPLPETRO.NS' },
  { symbol: 'SWANCORP', name: "Swan Corp", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SWANCORP.NS' },
  { symbol: 'SYNGENE', name: "Syngene International", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SYNGENE.NS' },
  { symbol: 'SYRMA', name: "Syrma SGS Technology", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'SYRMA.NS' },
  { symbol: 'TBOTEK', name: "TBO Tek", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TBOTEK.NS' },
  { symbol: 'TATACHEM', name: "Tata Chemicals", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TATACHEM.NS' },
  { symbol: 'TATATECH', name: "Tata Technologies", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TATATECH.NS' },
  { symbol: 'TTML', name: "Tata Teleservices (Maharashtra)", sector: 'TELECOM', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TTML.NS' },
  { symbol: 'TECHNOE', name: "Techno Electric & Engineering Company", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TECHNOE.NS' },
  { symbol: 'TEGA', name: "Tega Industries", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TEGA.NS' },
  { symbol: 'TEJASNET', name: "Tejas Networks", sector: 'TELECOM', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TEJASNET.NS' },
  { symbol: 'TENNIND', name: "Tenneco Clean Air India", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TENNIND.NS' },
  { symbol: 'RAMCOCEM', name: "The Ramco Cements", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'RAMCOCEM.NS' },
  { symbol: 'TIMKEN', name: "Timken India", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TIMKEN.NS' },
  { symbol: 'TITAGARH', name: "Titagarh Rail Systems", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TITAGARH.NS' },
  { symbol: 'TARIL', name: "Transformers And Rectifiers (India)", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TARIL.NS' },
  { symbol: 'TRAVELFOOD', name: "Travel Food Services", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TRAVELFOOD.NS' },
  { symbol: 'TRIDENT', name: "Trident", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TRIDENT.NS' },
  { symbol: 'TRITURBINE', name: "Triveni Turbine", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'TRITURBINE.NS' },
  { symbol: 'UCOBANK', name: "UCO Bank", sector: 'BANKING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'UCOBANK.NS' },
  { symbol: 'UTIAMC', name: "UTI Asset Management Company", sector: 'FINANCIAL_SERVICES', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'UTIAMC.NS' },
  { symbol: 'URBANCO', name: "Urban Company", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'URBANCO.NS' },
  { symbol: 'USHAMART', name: "Usha Martin", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'USHAMART.NS' },
  { symbol: 'VTL', name: "Vardhman Textiles", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'VTL.NS' },
  { symbol: 'VIJAYA', name: "Vijaya Diagnostic Centre", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'VIJAYA.NS' },
  { symbol: 'WELCORP', name: "Welspun Corp", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'WELCORP.NS' },
  { symbol: 'WELSPUNLIV', name: "Welspun Living", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'WELSPUNLIV.NS' },
  { symbol: 'WHIRLPOOL', name: "Whirlpool of India", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'WHIRLPOOL.NS' },
  { symbol: 'WOCKPHARMA', name: "Wockhardt", sector: 'HEALTHCARE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'WOCKPHARMA.NS' },
  { symbol: 'ZFCVINDIA', name: "ZF Commercial Vehicle Control Systems India", sector: 'AUTO', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ZFCVINDIA.NS' },
  { symbol: 'ZEEL', name: "Zee Entertainment Enterprises", sector: 'CONSUMER', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ZEEL.NS' },
  { symbol: 'ZENTEC', name: "Zen Technologies", sector: 'MANUFACTURING', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ZENTEC.NS' },
  { symbol: 'ZENSARTECH', name: "Zensar Technolgies", sector: 'TECHNOLOGY', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ZENSARTECH.NS' },
  { symbol: 'ZYDUSWELL', name: "Zydus Wellness", sector: 'FMCG', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ZYDUSWELL.NS' },
  { symbol: 'ECLERX', name: "eClerx Services", sector: 'INFRASTRUCTURE', mcap: 'SMALL', blueChip: false, dividendPayer: false, esgFriendly: false, yahooSymbol: 'ECLERX.NS' },
];
